name: Update CODEOWNERs

# For testing
# on: push

# For production
on:
  schedule:
    # https://crontab.guru/#5_8_*_*_1
    - cron: '5 8 * * 1'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  update:
    permissions:
      contents: write # for Git to git push
    runs-on: ubuntu-latest
    if: github.repository == 'DefinitelyTyped/DefinitelyTyped'

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4


      - run: git config --global user.email "typescriptbot@microsoft.com"
      - run: git config --global user.name "TypeScript Bot"

      - run: pnpm run update-codeowners

      - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5.0.0
        with:
          commit_author: 'TypeScript Bot <typescriptbot@microsoft.com>'
          commit_message: '🤖 Update CODEOWNERS'
          commit_user_email: 'typescriptbot@microsoft.com'
          commit_user_name: 'TypeScript Bot'
